# My Git-server dockerfile

FROM  centos:ssh

#设置系统时间为CTS时间
#RUN ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

#更新yum源
#RUN yum update -y
#安装工具
#RUN yum install -y which net-tools

#创建git账户
#也可以取消此步骤，然后将yum instal git提前，因为安装git服务后，将自动创建git账户
RUN useradd git

#配置git账户SSH，使其通过秘钥来认证
#创建.ssh目录
RUN mkdir -m 700 -p /home/git/.ssh
RUN chown git:git /home/git/.ssh
#配置公钥id_rsa_pub
RUN curl https://raw.githubusercontent.com/jiangkehot/jiang_test/master/id_rsa.pub >> /home/git/.ssh/authorized_keys
#修改authorized_keys的属性
RUN chown git:git /home/git/.ssh/authorized_keys
RUN chmod 600 /home/git/.ssh/authorized_keys
#修改SSH配置文件sshd_config
RUN sed -i 's/#RSAAuthentication/RSAAuthentication/g' /etc/ssh/sshd_config
RUN sed -i 's/#PubkeyAuthentication/PubkeyAuthentication/g' /etc/ssh/sshd_config
RUN sed -i 's/.ssh\/authorized_keys/\/home\/git\/.ssh\/authorized_keys/g' /etc/ssh/sshd_config

#配置git服务
#安装git服务
RUN yum install -y git
#启动git服务
#CMD systemctl start git
#初始化git库
RUN git init --bare /srv/git/zgctest.git
RUN chown -R git:git /srv/git

#禁止git账户登录shell,-s:指定为git-shell，使其不可以通过shell登录，git-shell的作用是用户登录后立即退出
RUN usermod -s `which git-shell` git

#启动SSH的守护进程,注意需要使用绝对路径
#CMD /usr/sbin/sshd -D
