# My Git-server dockerfile

FROM  centos:ssh

#创建git账户
RUN useradd git

#配置git账户，使其通过秘钥来认证
#创建.ssh目录
RUN mkdir -m 700 -p /home/git/.ssh
RUN chown git:git /home/git/.ssh
#配置公钥
RUN id_rsa_pub="ssh-rsa\ AAAAB3NzaC1yc2EAAAADAQABAAABAQDrH8ik1o0KwnzRN/nxjpABq5wnVi3WsM0IbZFp4QK5Ssr8z3PlVMRyrrcLemk1LEeWNiYEEzsvTQkGOhf69PHFSzzGWnWBdM2w1iE8ZWPaYdZg2Hk0BwbZqcRCdOQv7dkOgg/aL5C9e8VnaqpmW7aNE0Urcf1mTubzQU+zACvJ9X1NBwzSabgrY5F+gx0q6/hbbNxMraA1C3VDWqxk9WzcRUGlgU7AYp2yvMg5da7oUUbiJBfCumo6aCVuuTSAtWhszlESDqLg6CpEATXgepFU7OK/XZtt+T1RyqYRUOyFF1NVywWGJWILGtlTRov4lW7n+bumPRCV751a1fzlxa6X\ \“jiangkehot@gmail.com\”"
RUN echo $id_rsa_pub >> /home/git/.ssh/authorized_keys
#修改authorized_keys的属性
RUN chown git:git /home/git/.ssh/authorized_keys
RUN chmod 600 /home/git/.ssh/authorized_keys
#修改SSH配置文件sshd_config
RUN sed -i 's/#RSAAuthentication/RSAAuthentication/g' /etc/ssh/sshd_config
RUN sed -i 's/#PubkeyAuthentication/PubkeyAuthentication/g' /etc/ssh/sshd_config
RUN sed -i 's/.ssh\/authorized_keys/\/home\/git\/.ssh/authorized_keys/g' /etc/ssh/sshd_config

#安装git服务
RUN yum install -y git

#启动git服务
#CMD systemctl start git

#禁止git账户登录shell,-s:指定为git-shell，使其不可以通过shell登录，git-shell的作用是用户登录后立即退出
RUN usermod -s `which git-shell` git

#启动SSH的守护进程,注意需要使用绝对路径
#CMD /usr/sbin/sshd -D
