# My SSH dockerfile

FROM  centos:latest

#设置系统时间为CTS时间
RUN ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

#更新yum源
RUN yum update -y

#安装SSH sever服务
RUN yum install -y openssh-server

#创建秘钥
RUN ssh-keygen -q -t rsa -b 2048 -f /etc/ssh/ssh_host_rsa_key -N '';ssh-keygen -q -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key -N '';ssh-keygen -t dsa -f /etc/ssh/ssh_host_ed25519_key -N ''

#启动SSH的守护进程,注意需要使用绝对路径
CMD /usr/sbin/sshd -D

#创建SSH密码
RUN /bin/echo 'root:ssh123456' |chpasswd

#安装工具
RUN yum install -y which net-tools

#验证是否启动
#netstat -antp |grep sshd

#
