# My Git-server dockerfile

FROM  centos:ssh

#创建git账户,-s:指定为git-shell，使其不可以通过shell登录，git-shell的作用是用户登录后立即退出
RUN useradd -s `which git-shell` git

#配置git账户的SSH公钥
#创建.ssh目录
RUN mkdir -m 700 -p /home/git/.ssh
RUN chown git:git /home/git/.ssh
#获取公钥，通过设置变量id_rsa.pub，由用户输入得到
RUN echo "Please input your id_rsa.pub"
RUN read id_rsa_pub
RUN echo $id_rsa_pub >> /home/git/.ssh/authorized_keys
#修改authorized_keys的属性
RUN chown git:git /home/git/.ssh/authorized_keys
RUN chmod 600 /home/git/.ssh/authorized_keys
#修改SSH配置文件sshd_config
RUN sed -i 's/#RSAAuthentication/RSAAuthentication/g' /etc/ssh/sshd_config
RUN sed -i 's/#PubkeyAuthentication/PubkeyAuthentication/g' /etc/ssh/sshd_config
RUN sed -i 's/.ssh/authorized_keys/\/home\/git\/.ssh/authorized_keys/g' /etc/ssh/sshd_config

#安装git服务
RUN yum install -y git

#启动SSH的守护进程,注意需要使用绝对路径
CMD /usr/sbin/sshd -D
