#! /bin/bash
# VPN客户端启动脚本，服务器端安装请移步https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md

#read -p "输入服务器端IP：" VPN_SERVER_IP
# read -p "如果远程访问的话，输入客户端IP" VPN_LOCAL_IP
# 获取登录IP
#VPN_LOCAL_IP=`who am i | awk '{print $5}' | sed 's/(//g' | sed 's/)//g'`

# 创建 xl2tpd 控制文件：
mkdir -p /var/run/xl2tpd
touch /var/run/xl2tpd/l2tp-control

#重启服务：
# service strongswan restart
# service xl2tpd restart
/bin/systemctl restart strongswan.service
/bin/systemctl restart xl2tpd.service

sleep 3

#开始 IPsec 连接：
# CentOS/RHEL & Fedora
strongswan up myvpn

sleep 3

#开始 L2TP 连接：
echo "c myvpn" > /var/run/xl2tpd/l2tp-control

# 判断是否生成设备，如果没有发现，即字符串为0，则进入循环，直到找到设备然后跳出循环。//-z 字符串长度为0则为真
while [ -z $(ifconfig | egrep -v '^\s|^$' | awk '{print $1}'| grep 'ppp') ]; do
    sleep 1
done

#route add $VPN_SERVER_IP gw $(ip route | grep def | awk '{print $3}')
#route add $VPN_LOCAL_IP gw $(ip route | grep def | awk '{print $3}')

for ip in 34 45 52 64 74 172 216;do
  route add -net $ip.0.0.0/8 dev ppp0
done

#route add -net 172.217.0.0/16 dev ppp0
#route add default dev ppp0
#route add -host dev ppp0

#wget -qO- http://ipv4.icanhazip.com; echo
