#! /bin/bash
# VPN客户端启动脚本，服务器端安装请移步https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md

read -p "输入服务器端IP：" VPN_SERVER_IP
read -p "如果远程访问的话，输入客户端IP" VPN_LOCAL_IP
# 创建 xl2tpd 控制文件：
mkdir -p /var/run/xl2tpd
touch /var/run/xl2tpd/l2tp-control

#重启服务：
# service strongswan restart
# service xl2tpd restart
/bin/systemctl restart strongswan.service
/bin/systemctl restart xl2tpd.service

sleep 3

#开始 IPsec 连接：
# CentOS/RHEL & Fedora
strongswan up myvpn

#开始 L2TP 连接：
echo "c myvpn" > /var/run/xl2tpd/l2tp-control


sleep 3

route add $VPN_SERVER_IP gw $(ip route | grep def | awk '{print $3}')
route add $VPN_LOCAL_IP gw $(ip route | grep def | awk '{print $3}')

#route add default dev ppp0
route add -host dev ppp0

wget -qO- http://ipv4.icanhazip.com; echo
