# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define :manager do |manager|
    manager.vm.provider "virtualbox" do |v|
          v.customize ["modifyvm", :id, "--name", "manager", "--memory", "512","file", File.join(Dir.pwd, "ubuntu-xenial-16.04-cloudimg-console.log")]
    end
    manager.vm.box = "ubuntu/xenial64_20180710"
    manager.vm.hostname = "manager"
    manager.vm.network :private_network, ip: "192.168.56.101"
    # manager.vm.synced_folder "/Users/", "/Users/", type: "virtualbox"
    # manager.vm.synced_folder "/data", "/vagrant_data"
    # manager.vm.synced_folder "$PWD/ssh", "/home/vagrant/.ssh"
    manager.vm.network "forwarded_port", guest: 8500, host: 8500
    # manager.ssh.username = "jiangke"
    # manager.ssh.private_key_path = "~/.ssh/id_rsa" 
    # manager.ssh.forward_agent = true
    manager.vm.provision "shell", path: "vagrantup.sh"   
  end

  config.vm.define :node1 do |node1|
    node1.vm.provider "virtualbox" do |v|
          v.customize ["modifyvm", :id, "--name", "node1", "--memory", "512"]
    end
    node1.vm.box = "ubuntu/xenial64_20180710"
    node1.vm.hostname = "node1"
    node1.vm.network :private_network, ip: "192.168.56.104"
    node1.vm.provision "shell", path: "vagrantupnode.sh"
  end

  config.vm.define :node2 do |node2|
    node2.vm.provider "virtualbox" do |v|
          v.customize ["modifyvm", :id, "--name", "node2", "--memory", "512"]
    end
    node2.vm.box = "ubuntu/xenial64_20180710"
    node2.vm.hostname = "node2"
    node2.vm.network :private_network, ip: "192.168.56.105"
    node2.vm.provision "shell", path: "vagrantupnode.sh"
  end
end
