#! /bin/bash

set -e

# Install Ossfs
if ! /usr/bin/command ossfs; then
    rmp_ossfs='ossfs_1.80.5_centos7.0_x86_64.rpm'
    sudo yum localinstall -y ~/.local/src/aliyun-ossfs/$rmp_ossfs || sudo yum localinstall -y "http://gosspublic.alicdn.com/ossfs/$rmp_ossfs"
fi

# make bucket_point && 开机自动挂载
[ -f /root/.ssh/AccessKey ] || source ~/.ssh/AccessKey # mount脚本依赖/root/.ssh/AccessKey
arr_bucket=(djangotest jiangkehot univerdream-aliyun-bill univerdream-bj-registry)
ossfs_mount_point=/data/ossfs
ossfs_passwd_file=/etc/passwd-ossfs
ossfs_script_file=/etc/init.d/ossfs

touch $ossfs_passwd_file && chmod 640 $ossfs_passwd_file
touch $ossfs_script_file && chmod a+x $ossfs_script_file
for bucket in ${arr_bucket[@]} ;do
    if ! grep -q "$bucket" $ossfs_passwd_file; then
    	echo $bucket:$AccessKeyID:$AccessKeySecret >> $ossfs_passwd_file
    fi
    [ -d ${ossfs_mount_point}/${bucket} ] || mkdir ${ossfs_mount_point}/${bucket}
    if ! grep -q "$bucket" $ossfs_script_file; then
        echo "ossfs $bucket ${ossfs_mount_point}/${bucket} -ourl=http://oss-cn-beijing-internal.aliyuncs.com" >> $ossfs_script_file
    fi
done
. $ossfs_script_file
chkconfig ossfs on

## umount
#umount_ossfs()
#{
#  # root user: umount /tmp/ossfs 
#  # non-root user: fusermount -u /tmp/ossfs 
#  for dir in ${arr_bucket[@]} ;do 
#      umount ${ossfs_point}/${dir}/
#  done
#}
#umount_ossfs
