#! /bin/bash

set -e

[ -a ~/.bjadmin ] || su -

# Install Ossfs
if ! ossfs --version > /dev/null; then
    rmp_ossfs='ossfs_1.80.5_centos7.0_x86_64.rpm'
    [ -a ~/.bjadmin/src/aliyun-ossfs/$rmp_ossfs ] || wget -P ~/.bjadmin/src/aliyun-ossfs/ "http://gosspublic.alicdn.com/ossfs/$rmp_ossfs"
    sudo yum localinstall -y --installroot=~/.bjadmin/bin ~/.bjadmin/src/aliyun-ossfs/$rmp_ossfs
fi

arr_bucket=(djangotest jiangkehot univerdream-aliyun-bill univerdream-bj-registry univerdream-etc)
ossfs_point=/data/ossfs

# config
exiterr()  { echo "Error: $1" >&2; exit 1; }
# mount脚本依赖/root/.ssh/AccessKey
if [ ! -f /root/.ssh/AccessKey ]; then
	exiterr "/root/.ssh/AccessKey不存在，此脚本依赖文件/root/.ssh/AccessKey"
fi
source ~/.ssh/AccessKey
touch /etc/passwd-ossfs
for dir in ${arr_bucket[@]} ;do
    if ! grep -q "$dir" /etc/passwd-ossfs; then
    	echo $dir:$AccessKeyID:$AccessKeySecret >> /etc/passwd-ossfs
    fi
done
chmod 640 /etc/passwd-ossfs


# make directory && mount
for dir in ${arr_bucket[@]} ;do
    [ -d ${ossfs_point}/${dir} ] || mkdir ${ossfs_point}/${dir}
    ossfs $dir ${ossfs_point}/${dir} -ourl=http://oss-cn-beijing-internal.aliyuncs.com
done

# 开机自动挂载
chmod +x /etc/rc.d/rc.local
echo 'sleep 5' >> /etc/rc.local
for dir in ${arr_bucket[@]} ;do
  if ! grep -q "$dir" /etc/rc.d/rc.local; then
      echo "ossfs $dir ${ossfs_point}/${dir} -ourl=http://oss-cn-beijing-internal.aliyuncs.com" >> /etc/rc.local
  fi
done

## umount
#umount_ossfs()
#{
#  # root user: umount /tmp/ossfs 
#  # non-root user: fusermount -u /tmp/ossfs 
#  for dir in ${arr_bucket[@]} ;do 
#      umount ${ossfs_point}/${dir}/
#  done
#}
#umount_ossfs
