# .bash_profile
#shell命令：curl -fsSL https://raw.githubusercontent.com/jiangkehot/mytest/master/linux/bash_conf/bash_profile -o ~/.bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/bin
export PATH

#额外的配置文件
if [ -f ~/.mybashrc ]; then
  . ~/.mybashrc
fi

# history size 以及为history添加时间戳和输出格式
HISTSIZE=5000
HISTFILESIZE=5000
export HISTTIMEFORMAT='%F %T '

# 判断是否存在cdl命令
# [ -f `which cdl` ] && source `which cdl` >> /dev/null
# [ `which cdl` ] || curl -fsSL https://raw.githubusercontent.com/jiangkehot/mytest/master/linux/bash_conf/cdl.sh -o /usr/local/sbin/cdl && chmod +x /usr/local/sbin/cdl && source `which cdl` >> /dev/null
# 以下写法虽然无法简写在一行，但这才是正确且符合逻辑的。
if which cdl > /dev/null; then
	curl -fsSL https://raw.githubusercontent.com/jiangkehot/mytest/master/linux/bash_conf/cdl.sh -o /usr/local/sbin/cdl && chmod +x /usr/local/sbin/cdl
fi
source `which cdl` > /dev/null
