#! /bin/bash

# 向.bash_profile添加执行文件的命令

function mybashrc(){
	sudo tee -a ~/.bash_profile <<-'EOF'
	    
	    # 除.bashrc 外，新增个人设置
	    
	    if [ -f ~/.bashrc ]; then
		    . ~/.mybashrc
	    fi
	EOF
}

mybashrc
